// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)
const __dirname = new URL('.', import.meta.url).pathname

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      nativeBinding = require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./binding.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-android-arm64')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-android-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./binding.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-android-arm-eabi')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('./binding.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-win32-x64-msvc')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./binding.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-win32-ia32-msvc')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./binding.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-win32-arm64-msvc')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./binding.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@hyperse/hps-code-checker-rust-darwin-universal')
      const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-darwin-universal/package.json').version
      if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./binding.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-darwin-x64')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-darwin-x64/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./binding.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-darwin-arm64')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./binding.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-freebsd-x64')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./binding.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-freebsd-arm64')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./binding.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hyperse/hps-code-checker-rust-linux-x64-musl')
          const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./binding.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hyperse/hps-code-checker-rust-linux-x64-gnu')
          const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./binding.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hyperse/hps-code-checker-rust-linux-arm64-musl')
          const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./binding.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hyperse/hps-code-checker-rust-linux-arm64-gnu')
          const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./binding.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hyperse/hps-code-checker-rust-linux-arm-musleabihf')
          const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./binding.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hyperse/hps-code-checker-rust-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./binding.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hyperse/hps-code-checker-rust-linux-riscv64-musl')
          const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./binding.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@hyperse/hps-code-checker-rust-linux-riscv64-gnu')
          const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./binding.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-linux-ppc64-gnu')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./binding.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-linux-s390x-gnu')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./binding.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-openharmony-arm64')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./binding.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-openharmony-x64')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./binding.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@hyperse/hps-code-checker-rust-openharmony-arm')
        const bindingPackageVersion = require('@hyperse/hps-code-checker-rust-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '1.0.0-alpha.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0-alpha.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  try {
    nativeBinding = require('./binding.wasi.cjs')
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      loadErrors.push(err)
    }
  }
  if (!nativeBinding) {
    try {
      nativeBinding = require('@hyperse/hps-code-checker-rust-wasm32-wasi')
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        loadErrors.push(err)
      }
    }
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      { cause: loadErrors }
    )
  }
  throw new Error(`Failed to load native binding`)
}

const { registerRspackCodeCheckerPlugin, Assets, AsyncDependenciesBlock, Chunk, ChunkGraph, ChunkGroup, Chunks, CodeGenerationResult, CodeGenerationResults, ConcatenatedModule, ContextModule, Dependency, Diagnostics, EntryDataDto, EntryDataDTO, EntryDependency, EntryOptionsDto, EntryOptionsDTO, ExternalModule, JsCompilation, JsCompiler, JsContextModuleFactoryAfterResolveData, JsContextModuleFactoryBeforeResolveData, JsDependencies, JsEntries, JsExportsInfo, JsModuleGraph, JsResolver, JsResolverFactory, JsStats, KnownBuildInfo, Module, ModuleGraphConnection, NativeWatcher, NativeWatchResult, NormalModule, RawExternalItemFnCtx, ReadonlyResourceData, ResolverFactory, Sources, VirtualFileStore, JsVirtualFileStore, async, BuiltinPluginName, cleanupGlobalTrace, EnforceExtension, EXPECTED_RSPACK_CORE_VERSION, formatDiagnostic, JsLoaderState, JsRspackSeverity, loadBrowserslist, minify, minifySync, RawRuleSetConditionType, registerGlobalTrace, RegisterJsTapKind, sync, syncTraceEvent, transform, transformSync } = nativeBinding
export { registerRspackCodeCheckerPlugin }
export { Assets }
export { AsyncDependenciesBlock }
export { Chunk }
export { ChunkGraph }
export { ChunkGroup }
export { Chunks }
export { CodeGenerationResult }
export { CodeGenerationResults }
export { ConcatenatedModule }
export { ContextModule }
export { Dependency }
export { Diagnostics }
export { EntryDataDto }
export { EntryDataDTO }
export { EntryDependency }
export { EntryOptionsDto }
export { EntryOptionsDTO }
export { ExternalModule }
export { JsCompilation }
export { JsCompiler }
export { JsContextModuleFactoryAfterResolveData }
export { JsContextModuleFactoryBeforeResolveData }
export { JsDependencies }
export { JsEntries }
export { JsExportsInfo }
export { JsModuleGraph }
export { JsResolver }
export { JsResolverFactory }
export { JsStats }
export { KnownBuildInfo }
export { Module }
export { ModuleGraphConnection }
export { NativeWatcher }
export { NativeWatchResult }
export { NormalModule }
export { RawExternalItemFnCtx }
export { ReadonlyResourceData }
export { ResolverFactory }
export { Sources }
export { VirtualFileStore }
export { JsVirtualFileStore }
export { async }
export { BuiltinPluginName }
export { cleanupGlobalTrace }
export { EnforceExtension }
export { EXPECTED_RSPACK_CORE_VERSION }
export { formatDiagnostic }
export { JsLoaderState }
export { JsRspackSeverity }
export { loadBrowserslist }
export { minify }
export { minifySync }
export { RawRuleSetConditionType }
export { registerGlobalTrace }
export { RegisterJsTapKind }
export { sync }
export { syncTraceEvent }
export { transform }
export { transformSync }
