name: CI-hps-srv-rspack-plugin-import

on:
  push:
    branches:
      - main
      - major
      - minor
      - dev
    # Only consider those paths to trigger the action
    paths:
      - 'packages/**'
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/**'

  pull_request:
    branches:
      - main
      - major
      - minor
      - dev
    types:
      - opened
      - synchronize
      - reopened
    # Only consider those paths to trigger the action
    paths:
      - 'packages/**'
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust Environment
        uses: ./.github/actions/rust-setup

      - name: Setup Node.js Environment
        uses: ./.github/actions/node-env
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: Build hps-srv-rspack-plugin-import
        uses: ./.github/actions/rust-build
        with:
          working-directory: crates/hps-srv-rspack-plugin-import
          build-command: yarn build

      - name: Unit tests
        working-directory: crates/hps-srv-rspack-plugin-import
        run: |
          yarn test-unit
