name: CI-integrity

on:
  push:
    branches:
      - main
      - major
      - minor
    paths:
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - '.github/**'

  pull_request:
    branches:
      - main
      - major
      - minor
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: ./.github/actions/node-env
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: Check for duplicate dependencies in lock file
        run: |
          yarn dedupe --check

      - name: Check for yarn constraints.pro
        run: |
          yarn constraints

      # https://github.com/sverweij/dependency-cruiser
      # - name: Check monorepo dependency graph
      #   run: |
      #     yarn check:install
