name: github pages

on:
  push:
    branches: 
      - main  # Set a branch name to trigger deployment
    paths:
      - '.github/workflows/gh-pages.yml'
      - 'website/**'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: website
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js Environment
        uses: ./.github/actions/node-env
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable corepack
        run: corepack enable
  
      - name: Setup pnpm
        run: corepack prepare
            
      - name: 📥 Install Dependencies
        run: pnpm install

      - name: Unit tests
        run: |
          pnpm test

      - name: Build
        run: |
          pnpm build:ghpage

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/out